import { BRollClip, MusicTrack, VideoProject } from '../types';

// Curated Royalty-Free Sample Stock Videos for B-Roll & Backgrounds
export const SAMPLE_BROLL_LIBRARY: Array<{
  keyword: string;
  title: string;
  category: string;
  type: 'video' | 'image';
  url: string;
  thumbnail: string;
}> = [
  {
    keyword: 'growth money analytics rocket finance',
    title: 'Exponential Growth Chart & Cash',
    category: 'Finance & Growth',
    type: 'video',
    url: 'https://assets.mixkit.co/videos/preview/mixkit-hands-holding-and-counting-us-dollars-41221-large.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=600&auto=format&fit=crop&q=80',
  },
  {
    keyword: 'social media phone scrolling tiktok reels viral',
    title: 'Social Media Feed & Viral Notification',
    category: 'Social Media',
    type: 'video',
    url: 'https://assets.mixkit.co/videos/preview/mixkit-person-scrolling-on-a-smartphone-at-night-42861-large.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=600&auto=format&fit=crop&q=80',
  },
  {
    keyword: 'neon futuristic ai brain wave technology code',
    title: 'AI Neural Cyber Wave & Technology',
    category: 'Tech & AI',
    type: 'video',
    url: 'https://assets.mixkit.co/videos/preview/mixkit-blue-matrix-animation-with-digital-elements-43187-large.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
  },
  {
    keyword: 'stressed creator editing computer screen deadline',
    title: 'Stressed Creator Working Late',
    category: 'Lifestyle',
    type: 'video',
    url: 'https://assets.mixkit.co/videos/preview/mixkit-young-man-working-late-at-the-office-42777-large.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?w=600&auto=format&fit=crop&q=80',
  },
  {
    keyword: 'city timelapse night lights traffic speed fast',
    title: 'Urban Cyber City Hyperlapse',
    category: 'Cinematic',
    type: 'video',
    url: 'https://assets.mixkit.co/videos/preview/mixkit-traffic-at-night-in-a-busy-city-avenue-41618-large.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?w=600&auto=format&fit=crop&q=80',
  },
  {
    keyword: 'shocked surprised face wow celebration winner',
    title: 'Shocked Reaction & Joy Celebration',
    category: 'Emotions',
    type: 'video',
    url: 'https://assets.mixkit.co/videos/preview/mixkit-young-woman-with-a-surprised-expression-41979-large.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80',
  },
  {
    keyword: 'creative studio camera microphone podcast recording',
    title: 'Professional Creator Studio',
    category: 'Content Creation',
    type: 'video',
    url: 'https://assets.mixkit.co/videos/preview/mixkit-podcaster-speaking-into-a-microphone-43574-large.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=600&auto=format&fit=crop&q=80',
  },
];

// Curated Royalty-Free Music Library
export const SAMPLE_MUSIC_TRACKS: MusicTrack[] = [
  {
    id: 'm1',
    title: 'Phonk Heat Drive (Viral Beat)',
    artist: 'Creator Beats',
    mood: 'energetic',
    url: 'synth:energetic',
    volume: 0.45,
    bpm: 130,
    duration: 60,
    license: '100% Royalty-Free for Commercial Shorts & Reels',
  },
  {
    id: 'm2',
    title: 'Chill Lo-Fi Coffee Vibes',
    artist: 'Midnight Tape',
    mood: 'lofi',
    url: 'synth:lofi',
    volume: 0.35,
    bpm: 85,
    duration: 60,
    license: '100% Royalty-Free for Commercial Shorts & Reels',
  },
  {
    id: 'm3',
    title: 'Inspiring Tech Story Arc',
    artist: 'Future Horizon',
    mood: 'inspiring',
    url: 'synth:inspiring',
    volume: 0.4,
    bpm: 115,
    duration: 60,
    license: '100% Royalty-Free for Commercial Shorts & Reels',
  },
  {
    id: 'm4',
    title: 'Deep Dramatic Bass Cinematic',
    artist: 'Atlas Sound',
    mood: 'dramatic',
    url: 'synth:dramatic',
    volume: 0.5,
    bpm: 100,
    duration: 60,
    license: '100% Royalty-Free for Commercial Shorts & Reels',
  },
  {
    id: 'm5',
    title: 'Mysterious Suspense Pulse',
    artist: 'Dark Riddle',
    mood: 'suspense',
    url: 'synth:suspense',
    volume: 0.42,
    bpm: 120,
    duration: 60,
    license: '100% Royalty-Free for Commercial Shorts & Reels',
  },
];

// Demo Starter Presets (for instant 1-click test without uploading)
export const PRESET_PROJECTS: VideoProject[] = [
  {
    id: 'preset-talking-head-urdu-eng',
    title: 'Viral Creator Growth Secret (Urdu + Eng)',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-young-man-talking-to-the-camera-in-a-video-call-42774-large.mp4',
    videoDuration: 22.5,
    originalDuration: 26.0,
    editedDuration: 22.5,
    aspectRatio: '9:16',
    captionStyle: 'hormozi',
    captionLanguage: 'bilingual',
    isAutoEdited: true,
    autoResizeMode: 'fit_blur',
    hook: {
      enabled: true,
      text: 'STOP MAKING THIS MISTAKE! 🛑',
      urduText: 'یہ غلطی ابھی بند کریں! 🛑',
      style: 'zoom_punch',
      duration: 3.0,
      soundFx: 'whoosh',
      zoomLevel: 1.28,
      highlightColor: '#eab308',
    },
    cuts: [
      { id: 'cut1', start: 0.0, end: 0.7, duration: 0.7, type: 'silence', description: 'Dead air before speaking cut out', active: true },
      { id: 'cut2', start: 6.8, end: 7.9, duration: 1.1, type: 'filler', description: 'Filler sound "umm / yani" removed', active: true },
      { id: 'cut3', start: 14.1, end: 15.2, duration: 1.1, type: 'silence', description: 'Awkward mid-sentence pause shortened', active: true },
      { id: 'cut4', start: 20.2, end: 21.0, duration: 0.8, type: 'mistake', description: 'Stutter splice & seamless jump cut', active: true },
    ],
    captions: [
      {
        id: 'cap1',
        start: 0.7,
        end: 3.2,
        text: 'STOP making this HUGE video mistake!',
        urduText: 'یہ سب سے بڑی غلطی اب مت کریں!',
        words: [
          { text: 'STOP', urdu: 'روکیں', start: 0.7, end: 1.2, highlight: true, emoji: '🛑', color: '#ef4444' },
          { text: 'making', urdu: 'کرنا', start: 1.2, end: 1.6, highlight: false, emoji: '', color: '#ffffff' },
          { text: 'this', urdu: 'یہ', start: 1.6, end: 1.9, highlight: false, emoji: '', color: '#ffffff' },
          { text: 'HUGE', urdu: 'سب سے بڑی', start: 1.9, end: 2.5, highlight: true, emoji: '😱', color: '#eab308' },
          { text: 'MISTAKE!', urdu: 'غلطی!', start: 2.5, end: 3.2, highlight: true, emoji: '⚠️', color: '#38bdf8' },
        ],
      },
      {
        id: 'cap2',
        start: 3.3,
        end: 6.8,
        text: '99% of creators spend hours editing manually.',
        urduText: '99 فیصد کریئٹرز گھنٹوں ایڈیٹنگ میں ضائع کرتے ہیں۔',
        words: [
          { text: '99%', urdu: '99٪', start: 3.3, end: 4.0, highlight: true, emoji: '📊', color: '#22c55e' },
          { text: 'of', urdu: 'کے', start: 4.0, end: 4.3, highlight: false, emoji: '', color: '#ffffff' },
          { text: 'creators', urdu: 'کریئٹرز', start: 4.3, end: 5.0, highlight: true, emoji: '🎥', color: '#a855f7' },
          { text: 'spend', urdu: 'لگاتے', start: 5.0, end: 5.5, highlight: false, emoji: '', color: '#ffffff' },
          { text: 'HOURS', urdu: 'گھنٹوں', start: 5.5, end: 6.2, highlight: true, emoji: '⏳', color: '#ef4444' },
          { text: 'manually!', urdu: 'ہاتھ سے!', start: 6.2, end: 6.8, highlight: false, emoji: '', color: '#ffffff' },
        ],
      },
      {
        id: 'cap3',
        start: 8.0,
        end: 11.5,
        text: 'With ProAuto Edit, 1-click removes silences & adds captions.',
        urduText: 'پرو آٹو ایڈیٹ کے ساتھ، ایک کلک میں وقفے ختم اور سب ٹائٹلز لگ جاتے ہیں۔',
        words: [
          { text: 'ONE CLICK', urdu: 'ایک کلک', start: 8.0, end: 9.1, highlight: true, emoji: '⚡', color: '#38bdf8' },
          { text: 'removes', urdu: 'ختم کرے', start: 9.1, end: 9.7, highlight: false, emoji: '', color: '#ffffff' },
          { text: 'silences', urdu: 'وقفے', start: 9.7, end: 10.4, highlight: true, emoji: '✂️', color: '#eab308' },
          { text: '&', urdu: 'اور', start: 10.4, end: 10.7, highlight: false, emoji: '', color: '#ffffff' },
          { text: 'CAPTIONS!', urdu: 'سب ٹائٹلز!', start: 10.7, end: 11.5, highlight: true, emoji: '💬', color: '#4ade80' },
        ],
      },
      {
        id: 'cap4',
        start: 11.6,
        end: 15.8,
        text: 'Auto zoom hook, viral B-roll, and background music!',
        urduText: 'آٹو زوم ہک، وائرل بی رول اور بیک گراؤنڈ میوزک فوری!',
        words: [
          { text: 'AUTO', urdu: 'آٹو', start: 11.6, end: 12.2, highlight: true, emoji: '🚀', color: '#f43f5e' },
          { text: 'ZOOM', urdu: 'زوم', start: 12.2, end: 12.9, highlight: true, emoji: '🔍', color: '#38bdf8' },
          { text: 'HOOK,', urdu: 'ہک،', start: 12.9, end: 13.7, highlight: true, emoji: '🎣', color: '#eab308' },
          { text: 'B-ROLL,', urdu: 'بی رول،', start: 13.7, end: 14.7, highlight: true, emoji: '🎬', color: '#a855f7' },
          { text: 'MUSIC!', urdu: 'میوزک!', start: 14.7, end: 15.8, highlight: true, emoji: '🎵', color: '#22c55e' },
        ],
      },
      {
        id: 'cap5',
        start: 16.0,
        end: 22.0,
        text: 'Try it right now and watch your engagement explode!',
        urduText: 'ابھی آزمائیں اور اپنے ویوز کو 10 گنا بڑھائیں!',
        words: [
          { text: 'Try', urdu: 'آزمائیں', start: 16.0, end: 16.8, highlight: false, emoji: '', color: '#ffffff' },
          { text: 'it', urdu: 'اسے', start: 16.8, end: 17.3, highlight: false, emoji: '', color: '#ffffff' },
          { text: 'NOW!', urdu: 'ابھی!', start: 17.3, end: 18.5, highlight: true, emoji: '🔥', color: '#ef4444' },
          { text: 'EXPLODE', urdu: 'بڑھیں گے', start: 18.5, end: 20.0, highlight: true, emoji: '💥', color: '#38bdf8' },
          { text: 'VIEWS! 📈', urdu: 'ویوز! 📈', start: 20.0, end: 22.0, highlight: true, emoji: '🚀', color: '#22c55e' },
        ],
      },
    ],
    brolls: [
      {
        id: 'br1',
        start: 3.3,
        end: 6.5,
        keyword: 'stressed creator editing on computer late night',
        type: 'video',
        title: 'Stressed Creator Editing',
        url: 'https://assets.mixkit.co/videos/preview/mixkit-young-man-working-late-at-the-office-42777-large.mp4',
        thumbnail: 'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?w=600&auto=format&fit=crop&q=80',
        position: 'fullscreen',
        opacity: 0.95,
      },
      {
        id: 'br2',
        start: 8.2,
        end: 11.4,
        keyword: 'ai artificial intelligence neon energy wave',
        type: 'video',
        title: 'AI Automation Wave',
        url: 'https://assets.mixkit.co/videos/preview/mixkit-blue-matrix-animation-with-digital-elements-43187-large.mp4',
        thumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
        position: 'fullscreen',
        opacity: 0.95,
      },
      {
        id: 'br3',
        start: 18.5,
        end: 22.0,
        keyword: 'exponential growth rocket analytics chart',
        type: 'video',
        title: 'Explosive Viral Growth Chart',
        url: 'https://assets.mixkit.co/videos/preview/mixkit-hands-holding-and-counting-us-dollars-41221-large.mp4',
        thumbnail: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=600&auto=format&fit=crop&q=80',
        position: 'pip',
        opacity: 1.0,
      },
    ],
    music: SAMPLE_MUSIC_TRACKS[0],
    musicVolume: 0.35,
    autoDucking: true,
    soundEffects: [
      { id: 's1', time: 0.1, type: 'whoosh', volume: 0.9 },
      { id: 's2', time: 3.3, type: 'pop', volume: 0.8 },
      { id: 's3', time: 8.0, type: 'ding', volume: 0.85 },
      { id: 's4', time: 11.6, type: 'camera', volume: 0.75 },
      { id: 's5', time: 18.5, type: 'cash', volume: 0.9 },
    ],
    metadata: {
      title: 'Stop Making This HUGE Video Editing Mistake! 🚀',
      urduTitle: 'ویڈیو ایڈیٹنگ میں یہ غلطی اب کبھی مت کرنا! 😱',
      description: 'The secret 1-click AI workflow used by top creators on TikTok, Reels, and YouTube Shorts. Try ProAuto Edit today!',
      hashtags: ['#ProAutoEdit', '#YouTubeShorts', '#TikTokViral', '#ViralReels', '#VideoEditingHack', '#ContentCreator', '#UrduCreators'],
      score: 98,
      targetPlatform: 'all',
      platformSpecific: {
        tiktok: {
          title: 'This 1 AI video edit trick feels ILLEGAL 🤫📈',
          tags: ['#fyp', '#viral', '#foryou', '#creatorhack', '#editingtips', '#AItools'],
        },
        youtube: {
          title: 'How to Edit YouTube Shorts in 1-Click with AI (2026)',
          tags: ['#Shorts', '#AIEditing', '#ViralTips', '#YouTubeCreator', '#TrendingShorts'],
          description: 'Save 5+ hours every single day with AI silence removal, Hormozi captions, and automated B-roll overlays.',
        },
        facebook: {
          title: 'The AI tool that edits Facebook Reels automatically in seconds! ⚡',
          tags: ['#FacebookReels', '#ReelsViral', '#VideoCreator', '#TechTools', '#Automation'],
        },
      },
    },
  },
  {
    id: 'preset-fitness-vlog',
    title: 'Morning 5 AM Discipline Routine (Fitness Reel)',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-man-jogging-in-the-street-at-sunset-42007-large.mp4',
    videoDuration: 18.0,
    originalDuration: 21.0,
    editedDuration: 18.0,
    aspectRatio: '9:16',
    captionStyle: 'mrbeast',
    captionLanguage: 'english',
    isAutoEdited: true,
    autoResizeMode: 'fit_blur',
    hook: {
      enabled: true,
      text: 'WAKE UP AT 5 AM! ⏰⚡',
      urduText: 'صبح 5 بجے اٹھیں! ⏰',
      style: 'shake',
      duration: 3.0,
      soundFx: 'boom' as any,
      zoomLevel: 1.35,
      highlightColor: '#38bdf8',
    },
    cuts: [
      { id: 'c1', start: 0.0, end: 0.8, duration: 0.8, type: 'silence', description: 'Intro hesitation trimmed', active: true },
      { id: 'c2', start: 8.5, end: 9.7, duration: 1.2, type: 'filler', description: 'Heavy breath pause cut', active: true },
    ],
    captions: [
      {
        id: 'cp1',
        start: 0.8,
        end: 4.0,
        text: 'This 1 morning habit changed my entire life.',
        words: [
          { text: 'THIS', start: 0.8, end: 1.4, highlight: true, emoji: '🔥', color: '#38bdf8' },
          { text: '1', start: 1.4, end: 1.8, highlight: true, emoji: '⚡', color: '#eab308' },
          { text: 'MORNING', start: 1.8, end: 2.5, highlight: true, emoji: '🌅', color: '#22c55e' },
          { text: 'HABIT', start: 2.5, end: 3.1, highlight: false, emoji: '', color: '#ffffff' },
          { text: 'CHANGED', start: 3.1, end: 3.6, highlight: false, emoji: '', color: '#ffffff' },
          { text: 'EVERYTHING!', start: 3.6, end: 4.0, highlight: true, emoji: '💯', color: '#f43f5e' },
        ],
      },
      {
        id: 'cp2',
        start: 4.1,
        end: 8.5,
        text: 'No alarms snoozed. No excuses. Just pure execution.',
        words: [
          { text: 'NO', start: 4.1, end: 4.6, highlight: true, emoji: '🚫', color: '#ef4444' },
          { text: 'SNOOZE.', start: 4.6, end: 5.5, highlight: true, emoji: '⏰', color: '#eab308' },
          { text: 'NO', start: 5.5, end: 6.0, highlight: true, emoji: '❌', color: '#ef4444' },
          { text: 'EXCUSES.', start: 6.0, end: 7.0, highlight: true, emoji: '💪', color: '#38bdf8' },
          { text: 'PURE', start: 7.0, end: 7.6, highlight: false, emoji: '', color: '#ffffff' },
          { text: 'EXECUTION!', start: 7.6, end: 8.5, highlight: true, emoji: '🚀', color: '#22c55e' },
        ],
      },
    ],
    brolls: [
      {
        id: 'br_fit1',
        start: 4.2,
        end: 8.2,
        keyword: 'city sunrise hyperlapse running athlete',
        type: 'video',
        title: 'Sunrise City Runner',
        url: 'https://assets.mixkit.co/videos/preview/mixkit-traffic-at-night-in-a-busy-city-avenue-41618-large.mp4',
        thumbnail: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?w=600&auto=format&fit=crop&q=80',
        position: 'fullscreen',
        opacity: 0.95,
      },
    ],
    music: SAMPLE_MUSIC_TRACKS[2],
    musicVolume: 0.4,
    autoDucking: true,
    soundEffects: [
      { id: 'sf_1', time: 0.1, type: 'whoosh', volume: 0.9 },
      { id: 'sf_2', time: 4.1, type: 'sub_drop', volume: 0.85 },
    ],
    metadata: {
      title: 'How Waking Up at 5 AM Changed Everything 🔥',
      urduTitle: 'صبح 5 بجے اٹھنے کی اصل طاقت 💪',
      description: 'Discipline beats motivation every single time. Start your morning protocol today!',
      hashtags: ['#MorningRoutine', '#Discipline', '#Shorts', '#Reels', '#FitnessMotivation'],
      score: 95,
      targetPlatform: 'all',
      platformSpecific: {
        tiktok: { title: 'The 5 AM protocol nobody talks about 🤫⚡', tags: ['#5amclub', '#grindset', '#discipline'] },
        youtube: { title: 'My 5 AM Morning Routine That Boosted 10x Productivity', tags: ['#Shorts', '#MorningRoutine', '#Productivity'] },
        facebook: { title: 'Stop making excuses. Wake up early and execute!', tags: ['#Motivation', '#DailyGrind'] },
      },
    },
  },
];

export const SAMPLE_PROJECTS = PRESET_PROJECTS;
